version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: mcscanner
      POSTGRES_PASSWORD: mcscannerpass
      POSTGRES_DB: mcdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  controller:
    build: .
    container_name: controller
    command: python controller/main.py
    env_file: .env
    depends_on:
      - redis
      - postgres

  dashboard:
    build: .
    container_name: dashboard
    command: python controller/dashboard.py
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
      - postgres


volumes:
  pgdata:
